version: '3.8'

networks:
  shopping-network:
    driver: bridge

services:
  consul:
    image: consul:1.14.8
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - shopping-network

  product-service:
    image: product-service:1.0.0
    ports:
      - "10120:10120"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    networks:
      - shopping-network
    depends_on:
      - consul

  gateway-api:
    image: gateway-api:1.0.0
    ports:
      - "10110:10110"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    networks:
      - shopping-network
    depends_on:
      - consul
      - product-service

  web-portal:  # New service for the Vue.js application
    image: web-portal:1.0.0
    ports:
      - "80:80"  # Expose the Nginx server on port 80
    networks:
      - shopping-network
    depends_on:
      - consul
      - gateway-api
      - product-service
