server:
  port: 10120

spring:
  application:
    name: product-service
  web:
    resources:
      static-locations: classpath:/static/
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

  datasource:
    url: jdbc:mariadb://access-point.xyz:3306/shopping
    username: shopping
    password: I@riFuJs30#zE9@J
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.shoppingapp.productservice.model
  #configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl